### ISSUE TITLE
关于ArgCommand的小建议

### ISSUE THREAD

**Issue by mengpf** [PigeonYuze/YamlBot#6]
感觉加个参数，控制指令为前缀或者后缀更好一点。
举个例子：如果我要用这个写一个查询天气的，天气作为指令词，天气上海就很奇怪，上海天气就正常多了。

**Comment by PigeonYuze** [comment]
大概会在1.5.0实现该功能，目前计划下个版本只是增加一部分的模板支持（如反射调用`Java`方法，以及对群荣誉的调用支持）

大约应该可以在这周末实现吧？
